import type { Agent, Flight } from "./types";

export const HOTEL_COMMISSION_RATE = 0.01;

export const AGENTS: Agent[] = [
  {
    id: "agent-sarah",
    name: "Sarah Chen",
    initials: "SC",
    email: "sarah.chen@atlastravel.com",
    avatarTint: "from-indigo-500 to-violet-500",
  },
  {
    id: "agent-marco",
    name: "Marco Albini",
    initials: "MA",
    email: "marco.albini@atlastravel.com",
    avatarTint: "from-amber-500 to-orange-500",
  },
  {
    id: "agent-priya",
    name: "Priya Raman",
    initials: "PR",
    email: "priya.raman@atlastravel.com",
    avatarTint: "from-emerald-500 to-teal-500",
  },
  {
    id: "agent-jonas",
    name: "Jonas Weber",
    initials: "JW",
    email: "jonas.weber@atlastravel.com",
    avatarTint: "from-sky-500 to-cyan-500",
  },
];

export const ACTIVE_AGENT_ID = "agent-sarah";

// Today is 2026-05-28 in the demo timeline; all dates are in the future.
export const FLIGHTS: Flight[] = [
  {
    id: "FL-9421",
    bookingRef: "ATL-9421",
    passengerName: "Eleanor & James Whitfield",
    partySize: 2,
    email: "eleanor.whitfield@gmail.com",
    phone: "+1 415 555 0142",
    origin: "JFK",
    originCity: "New York",
    destination: "LIS",
    destinationCity: "Lisbon",
    departureDate: "2026-06-04",
    returnDate: "2026-06-12",
    flightCostUsd: 2840,
    hotelCostUsd: 3650,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9438",
    bookingRef: "ATL-9438",
    passengerName: "Yuki Tanaka",
    partySize: 1,
    email: "yuki.tanaka@hey.com",
    phone: "+81 90 5555 0188",
    origin: "SFO",
    originCity: "San Francisco",
    destination: "CDG",
    destinationCity: "Paris",
    departureDate: "2026-06-09",
    returnDate: "2026-06-16",
    flightCostUsd: 1980,
    hotelCostUsd: 2420,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9445",
    bookingRef: "ATL-9445",
    passengerName: "Amelia & Ravi Kapoor",
    partySize: 2,
    email: "amelia.kapoor@outlook.com",
    phone: "+44 7700 900142",
    origin: "LHR",
    originCity: "London",
    destination: "HND",
    destinationCity: "Tokyo",
    departureDate: "2026-06-18",
    returnDate: "2026-07-02",
    flightCostUsd: 4220,
    hotelCostUsd: 4180,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9452",
    bookingRef: "ATL-9452",
    passengerName: "Devon Park",
    partySize: 1,
    email: "devon.park@protonmail.com",
    phone: "+1 312 555 0173",
    origin: "ORD",
    originCity: "Chicago",
    destination: "BCN",
    destinationCity: "Barcelona",
    departureDate: "2026-07-03",
    returnDate: "2026-07-11",
    flightCostUsd: 1560,
    hotelCostUsd: 2890,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9460",
    bookingRef: "ATL-9460",
    passengerName: "The Okonkwo Family",
    partySize: 4,
    email: "n.okonkwo@gmail.com",
    phone: "+1 646 555 0119",
    origin: "EWR",
    originCity: "Newark",
    destination: "ROM",
    destinationCity: "Rome",
    departureDate: "2026-07-15",
    returnDate: "2026-07-26",
    flightCostUsd: 5680,
    hotelCostUsd: 6240,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9471",
    bookingRef: "ATL-9471",
    passengerName: "Hannah Lindqvist",
    partySize: 1,
    email: "hannah.lindqvist@icloud.com",
    phone: "+46 70 555 0144",
    origin: "ARN",
    originCity: "Stockholm",
    destination: "MEX",
    destinationCity: "Mexico City",
    departureDate: "2026-08-02",
    returnDate: "2026-08-13",
    flightCostUsd: 1820,
    hotelCostUsd: 1640,
    agentId: "agent-sarah",
    status: "open",
  },
  {
    id: "FL-9382",
    bookingRef: "ATL-9382",
    passengerName: "Carla Mendoza",
    partySize: 2,
    email: "carla.mendoza@gmail.com",
    phone: "+34 600 555 0188",
    origin: "MAD",
    originCity: "Madrid",
    destination: "LIM",
    destinationCity: "Lima",
    departureDate: "2026-06-22",
    returnDate: "2026-07-04",
    flightCostUsd: 2240,
    hotelCostUsd: 1980,
    agentId: "agent-sarah",
    status: "upsold",
  },
  {
    id: "FL-9396",
    bookingRef: "ATL-9396",
    passengerName: "Theodore Brennan",
    partySize: 1,
    email: "ted.brennan@hotmail.com",
    phone: "+353 86 555 0166",
    origin: "DUB",
    originCity: "Dublin",
    destination: "REK",
    destinationCity: "Reykjavík",
    departureDate: "2026-06-06",
    returnDate: "2026-06-13",
    flightCostUsd: 920,
    hotelCostUsd: 2160,
    agentId: "agent-sarah",
    status: "upsold",
  },
  {
    id: "FL-9404",
    bookingRef: "ATL-9404",
    passengerName: "Mei Lin & Anthony Hoang",
    partySize: 2,
    email: "mei.hoang@gmail.com",
    phone: "+1 213 555 0102",
    origin: "LAX",
    originCity: "Los Angeles",
    destination: "DPS",
    destinationCity: "Bali",
    departureDate: "2026-07-09",
    returnDate: "2026-07-22",
    flightCostUsd: 3460,
    hotelCostUsd: 3820,
    agentId: "agent-sarah",
    status: "upsold",
  },
  {
    id: "FL-9412",
    bookingRef: "ATL-9412",
    passengerName: "Ben Gold",
    partySize: 1,
    email: "ben.gold@gmail.com",
    phone: "+1 917 555 0167",
    origin: "BOS",
    originCity: "Boston",
    destination: "ATH",
    destinationCity: "Athens",
    departureDate: "2026-09-04",
    returnDate: "2026-09-14",
    flightCostUsd: 1740,
    hotelCostUsd: 2880,
    agentId: "agent-sarah",
    status: "declined",
  },
  {
    id: "FL-9418",
    bookingRef: "ATL-9418",
    passengerName: "Sofia Romano",
    partySize: 3,
    email: "sofia.romano@gmail.com",
    phone: "+39 333 555 0143",
    origin: "FCO",
    originCity: "Rome",
    destination: "JFK",
    destinationCity: "New York",
    departureDate: "2026-06-29",
    returnDate: "2026-07-08",
    flightCostUsd: 2920,
    hotelCostUsd: 3540,
    agentId: "agent-sarah",
    status: "declined",
  },
  {
    id: "FL-9358",
    bookingRef: "ATL-9358",
    passengerName: "Olivia & Daniel Park",
    partySize: 2,
    email: "olivia.park@gmail.com",
    phone: "+1 206 555 0118",
    origin: "SEA",
    originCity: "Seattle",
    destination: "VIE",
    destinationCity: "Vienna",
    departureDate: "2026-06-20",
    returnDate: "2026-06-28",
    flightCostUsd: 2680,
    hotelCostUsd: 2240,
    agentId: "agent-sarah",
    status: "past",
  },

  // Other agents' flights — used by the agency leaderboard.
  {
    id: "FL-9501",
    bookingRef: "ATL-9501",
    passengerName: "Hector Alvarez",
    partySize: 2,
    email: "h.alvarez@gmail.com",
    phone: "+34 600 555 0211",
    origin: "BCN",
    originCity: "Barcelona",
    destination: "JFK",
    destinationCity: "New York",
    departureDate: "2026-07-19",
    returnDate: "2026-07-30",
    flightCostUsd: 2180,
    hotelCostUsd: 3120,
    agentId: "agent-marco",
    status: "upsold",
  },
  {
    id: "FL-9508",
    bookingRef: "ATL-9508",
    passengerName: "Imani Williams",
    partySize: 1,
    email: "imani.w@gmail.com",
    phone: "+1 404 555 0188",
    origin: "ATL",
    originCity: "Atlanta",
    destination: "DKR",
    destinationCity: "Dakar",
    departureDate: "2026-08-12",
    returnDate: "2026-08-22",
    flightCostUsd: 1980,
    hotelCostUsd: 2640,
    agentId: "agent-marco",
    status: "upsold",
  },
  {
    id: "FL-9514",
    bookingRef: "ATL-9514",
    passengerName: "Liam Bauer",
    partySize: 2,
    email: "liam.bauer@gmail.com",
    phone: "+49 151 555 0177",
    origin: "FRA",
    originCity: "Frankfurt",
    destination: "SIN",
    destinationCity: "Singapore",
    departureDate: "2026-07-04",
    returnDate: "2026-07-15",
    flightCostUsd: 3120,
    hotelCostUsd: 3940,
    agentId: "agent-marco",
    status: "open",
  },
  {
    id: "FL-9519",
    bookingRef: "ATL-9519",
    passengerName: "Saanvi Kumar",
    partySize: 2,
    email: "saanvi.k@gmail.com",
    phone: "+91 98 555 0198",
    origin: "BOM",
    originCity: "Mumbai",
    destination: "LHR",
    destinationCity: "London",
    departureDate: "2026-06-30",
    returnDate: "2026-07-09",
    flightCostUsd: 1640,
    hotelCostUsd: 2780,
    agentId: "agent-priya",
    status: "upsold",
  },
  {
    id: "FL-9526",
    bookingRef: "ATL-9526",
    passengerName: "Andrea Bianchi",
    partySize: 1,
    email: "andrea.b@gmail.com",
    phone: "+39 333 555 0166",
    origin: "MXP",
    originCity: "Milan",
    destination: "CPT",
    destinationCity: "Cape Town",
    departureDate: "2026-08-22",
    returnDate: "2026-09-04",
    flightCostUsd: 2980,
    hotelCostUsd: 3380,
    agentId: "agent-priya",
    status: "open",
  },
  {
    id: "FL-9530",
    bookingRef: "ATL-9530",
    passengerName: "Greta Nilsen",
    partySize: 2,
    email: "greta.nilsen@gmail.com",
    phone: "+47 90 555 0144",
    origin: "OSL",
    originCity: "Oslo",
    destination: "KEF",
    destinationCity: "Reykjavík",
    departureDate: "2026-06-26",
    returnDate: "2026-07-02",
    flightCostUsd: 880,
    hotelCostUsd: 1840,
    agentId: "agent-jonas",
    status: "upsold",
  },
  {
    id: "FL-9537",
    bookingRef: "ATL-9537",
    passengerName: "Felix Carter",
    partySize: 1,
    email: "felix.carter@gmail.com",
    phone: "+1 718 555 0122",
    origin: "JFK",
    originCity: "New York",
    destination: "CUN",
    destinationCity: "Cancún",
    departureDate: "2026-07-12",
    returnDate: "2026-07-19",
    flightCostUsd: 720,
    hotelCostUsd: 1980,
    agentId: "agent-jonas",
    status: "declined",
  },
];
